apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rap-proxy
spec:
  selector:
    matchLabels:
      app: rap-proxy
  template:
    metadata:
      labels:
        app: rap-proxy
    spec:
      serviceAccountName: rap-proxy-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: rap-proxy
        image: govind72/rap-proxy:lates
        ports:
        - containerPort: 80
          hostPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: THRESHOLD
          value: "0.8"
        - name: APP_LABEL
          value: "app=sample-app"
        - name: APP_PORT
          value: "8000"
        - name: UPDATE_INTERVAL
          value: "10"
      tolerations:
      - operator: Exists
