apiVersion: v1
kind: ServiceAccount
metadata:
  name: rap-proxy-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rap-proxy-role
rules:
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["get","list"]
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rap-proxy-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rap-proxy-role
subjects:
- kind: ServiceAccount
  name: rap-proxy-sa
  namespace: default
